In [1]:
import pandas as pd
import numpy as np
from geopy import geocoders
from geopy.geocoders import Nominatim
import wbgapi as wb 
from pandas_profiling import ProfileReport

In [2]:
df_ec_v1 = wb.series.info("NY.GDP.MKTP.CD")
df_ec_v1

id              value
--------------  -----------------
NY.GDP.MKTP.CD  GDP (current US$)
                1 elements

In [23]:
wb.region.info()

code    name
------  -----------------------------------------------------
AFE     Africa Eastern and Southern
AFR     Africa
AFW     Africa Western and Central
ARB     Arab World
CAA     Sub-Saharan Africa (IFC classification)
CEA     East Asia and the Pacific (IFC classification)
CEB     Central Europe and the Baltics
CEU     Europe and Central Asia (IFC classification)
CLA     Latin America and the Caribbean (IFC classification)
CME     Middle East and North Africa (IFC classification)
CSA     South Asia (IFC classification)
CSS     Caribbean small states
EAP     East Asia & Pacific (excluding high income)
EAR     Early-demographic dividend
EAS     East Asia & Pacific
ECA     Europe & Central Asia (excluding high income)
ECS     Europe & Central Asia
EMU     Euro area
EUU     European Union
FCS     Fragile and conflict affected situations
HPC     Heavily indebted poor countries (HIPC)
LAC     Latin America & Caribbean (excluding high income)
LCN     Latin America & Caribbean
LDC     Least developed countries: UN classification
LTE     Late-demographic dividend
MDE     Middle East (developing only)
MEA     Middle East & North Africa
MNA     Middle East & North Africa (excluding high income)
NAC     North America
NAF     North Africa
NRS     Non-resource rich Sub-Saharan Africa countries
OED     OECD members
OSS     Other small states
PRE     Pre-demographic dividend
PSS     Pacific island small states
PST     Post-demographic dividend
RRS     Resource rich Sub-Saharan Africa countries
SAS     South Asia
SSA     Sub-Saharan Africa (excluding high income)
SSF     Sub-Saharan Africa
SST     Small states
SXZ     Sub-Saharan Africa excluding South Africa
WLD     World
XZN     Sub-Saharan Africa excluding South Africa and Nigeria
        44 elements

In [24]:
wb.region.members('WLD')

{'ABW',
 'AFG',
 'AGO',
 'ALB',
 'AND',
 'ARE',
 'ARG',
 'ARM',
 'ASM',
 'ATG',
 'AUS',
 'AUT',
 'AZE',
 'BDI',
 'BEL',
 'BEN',
 'BFA',
 'BGD',
 'BGR',
 'BHR',
 'BHS',
 'BIH',
 'BLR',
 'BLZ',
 'BMU',
 'BOL',
 'BRA',
 'BRB',
 'BRN',
 'BTN',
 'BWA',
 'CAF',
 'CAN',
 'CHE',
 'CHI',
 'CHL',
 'CHN',
 'CIV',
 'CMR',
 'COD',
 'COG',
 'COL',
 'COM',
 'CPV',
 'CRI',
 'CUB',
 'CUW',
 'CYM',
 'CYP',
 'CZE',
 'DEU',
 'DJI',
 'DMA',
 'DNK',
 'DOM',
 'DZA',
 'ECU',
 'EGY',
 'ERI',
 'ESP',
 'EST',
 'ETH',
 'FIN',
 'FJI',
 'FRA',
 'FRO',
 'FSM',
 'GAB',
 'GBR',
 'GEO',
 'GHA',
 'GIB',
 'GIN',
 'GMB',
 'GNB',
 'GNQ',
 'GRC',
 'GRD',
 'GRL',
 'GTM',
 'GUM',
 'GUY',
 'HKG',
 'HND',
 'HRV',
 'HTI',
 'HUN',
 'IDN',
 'IMN',
 'IND',
 'IRL',
 'IRN',
 'IRQ',
 'ISL',
 'ISR',
 'ITA',
 'JAM',
 'JOR',
 'JPN',
 'KAZ',
 'KEN',
 'KGZ',
 'KHM',
 'KIR',
 'KNA',
 'KOR',
 'KWT',
 'LAO',
 'LBN',
 'LBR',
 'LBY',
 'LCA',
 'LIE',
 'LKA',
 'LSO',
 'LTU',
 'LUX',
 'LVA',
 'MAC',
 'MAF',
 'MAR',
 'MCO',
 'MDA',
 'MDG',
 'MDV',
 'MEX',
 'MHL',
 'MKD',
 'MLI',
 'MLT',
 'MMR',
 'MNE',
 'MNG',
 'MNP',
 'MOZ',
 'MRT',
 'MUS',
 'MWI',
 'MYS',
 'NAM',
 'NCL',
 'NER',
 'NGA',
 'NIC',
 'NLD',
 'NOR',
 'NPL',
 'NRU',
 'NZL',
 'OMN',
 'PAK',
 'PAN',
 'PER',
 'PHL',
 'PLW',
 'PNG',
 'POL',
 'PRI',
 'PRK',
 'PRT',
 'PRY',
 'PSE',
 'PYF',
 'QAT',
 'ROU',
 'RUS',
 'RWA',
 'SAU',
 'SDN',
 'SEN',
 'SGP',
 'SLB',
 'SLE',
 'SLV',
 'SMR',
 'SOM',
 'SRB',
 'SSD',
 'STP',
 'SUR',
 'SVK',
 'SVN',
 'SWE',
 'SWZ',
 'SXM',
 'SYC',
 'SYR',
 'TCA',
 'TCD',
 'TGO',
 'THA',
 'TJK',
 'TKM',
 'TLS',
 'TON',
 'TTO',
 'TUN',
 'TUR',
 'TUV',
 'TWN',
 'TZA',
 'UGA',
 'UKR',
 'URY',
 'USA',
 'UZB',
 'VCT',
 'VEN',
 'VGB',
 'VIR',
 'VNM',
 'VUT',
 'WSM',
 'XKX',
 'YEM',
 'ZAF',
 'ZMB',
 'ZWE'}

In [32]:
#df_ec = wb.series.get("NY.GDP.MKTP.CD")
df_data_ec = wb.data.DataFrame('NY.GDP.MKTP.CD',wb.region.members('WLD'))

df_data_ec = df_data_ec.reset_index()
df_data_ec = pd.DataFrame(df_data_ec)
df_data_ec

/Users/eduardoarroyo/opt/anaconda3/lib/python3.9/site-packages/wbgapi/data.py:327: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dummy = pd.Series()    # empty series - never assigned actual values

,economy,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
0,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.549721e+09,2.534637e+09,2.727850e+09,2.790849e+09,2.962905e+09,2.983637e+09,3.092430e+09,3.202189e+09,NaN,NaN
1,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,...,1.780511e+10,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10
2,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.117897e+11,1.280529e+11,1.367099e+11,1.457122e+11,1.161936e+11,1.011239e+11,1.221238e+11,1.013532e+11,8.941719e+10,5.837598e+10
3,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.289076e+10,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540024e+10,1.488763e+10
4,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.629204e+09,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.341737e+09,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09
213,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.272642e+10,3.540134e+10,4.041524e+10,4.322859e+10,4.244510e+10,3.131737e+10,2.684013e+10,2.160614e+10,NaN,NaN
214,ZAF,7.575397e+09,7.972997e+09,8.497997e+09,9.423396e+09,1.037400e+10,1.133440e+10,1.235500e+10,1.377739e+10,1.489459e+10,...,4.582015e+11,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11
215,ZMB,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,1.605857e+09,...,2.345952e+10,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10
216,ZWE,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,1.479600e+09,...,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10

In [15]:
cols = ['YR' + str(i) for i in range(1960,2021)]
print(cols)

['YR1960', 'YR1961', 'YR1962', 'YR1963', 'YR1964', 'YR1965', 'YR1966', 'YR1967', 'YR1968', 'YR1969', 'YR1970', 'YR1971', 'YR1972', 'YR1973', 'YR1974', 'YR1975', 'YR1976', 'YR1977', 'YR1978', 'YR1979', 'YR1980', 'YR1981', 'YR1982', 'YR1983', 'YR1984', 'YR1985', 'YR1986', 'YR1987', 'YR1988', 'YR1989', 'YR1990', 'YR1991', 'YR1992', 'YR1993', 'YR1994', 'YR1995', 'YR1996', 'YR1997', 'YR1998', 'YR1999', 'YR2000', 'YR2001', 'YR2002', 'YR2003', 'YR2004', 'YR2005', 'YR2006', 'YR2007', 'YR2008', 'YR2009', 'YR2010', 'YR2011', 'YR2012', 'YR2013', 'YR2014', 'YR2015', 'YR2016', 'YR2017', 'YR2018', 'YR2019', 'YR2020']

In [16]:
df_melted = df_data_ec.melt(id_vars=['economy'],
                            value_vars=cols)
df_melted

     economy variable         value
0        AUT   YR1960  6.592694e+09
1        BEL   YR1960  1.165872e+10
2        BGR   YR1960           NaN
3        CYP   YR1960           NaN
4        CZE   YR1960           NaN
...      ...      ...           ...
1642     PRT   YR2020  2.285392e+11
1643     ROU   YR2020  2.487156e+11
1644     SVK   YR2020  1.051726e+11
1645     SVN   YR2020  5.358961e+10
1646     SWE   YR2020  5.412201e+11

[1647 rows x 3 columns]

In [31]:
df_data_ec_v2 = wb.economy.DataFrame(skipAggs=False)
df_data_ec_v2 = pd.DataFrame(df_data_ec_v2)
df_data_ec_v2.to_csv("../data/economies_wb.csv")